/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 02:04:47 GMT 2018
 */

package spark.resource;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import spark.resource.UriPath;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UriPath_ESTest extends UriPath_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UriPath.canonical(".-");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UriPath.canonical("'G");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UriPath.canonical("*");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = UriPath.canonical(".Q,=;Z/A");
      assertEquals(".Q,=;Z/A", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = UriPath.canonical("/tA");
      assertEquals("/tA", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = UriPath.canonical(".");
      assertEquals("", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = UriPath.canonical("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String string0 = UriPath.canonical(".7/zEGs~^ \"YXS");
      assertEquals(".7/zEGs~^ \"YXS", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      String string0 = UriPath.canonical((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      UriPath uriPath0 = new UriPath();
  }
}
