/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 00:53:05 GMT 2018
 */

package spark.embeddedserver.jetty;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.jetty.server.Server;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import spark.embeddedserver.jetty.JettyServer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JettyServer_ESTest extends JettyServer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Server server0 = JettyServer.create(200, 60000, 0);
      assertFalse(server0.isStarted());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Server server0 = JettyServer.create(87, 0, 155);
      assertTrue(server0.isStopped());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Server server0 = JettyServer.create(0, 0, 0);
      assertFalse(server0.isStarted());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      JettyServer.create(Integer.MAX_VALUE, Integer.MAX_VALUE, 2576);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Server server0 = JettyServer.create(1, (-78), (-78));
      assertEquals("STOPPED", server0.getState());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Server server0 = JettyServer.create((-78), (-78), 1);
      assertEquals(30000L, server0.getStopTimeout());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JettyServer jettyServer0 = new JettyServer();
  }
}
