/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 02:04:45 GMT 2018
 */

package spark.serialization;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.OutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import spark.serialization.BytesSerializer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BytesSerializer_ESTest extends BytesSerializer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BytesSerializer bytesSerializer0 = new BytesSerializer();
      // Undeclared exception!
      try { 
        bytesSerializer0.process((OutputStream) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("spark.serialization.BytesSerializer", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BytesSerializer bytesSerializer0 = new BytesSerializer();
      boolean boolean0 = bytesSerializer0.canProcess("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BytesSerializer bytesSerializer0 = new BytesSerializer();
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      bytesSerializer0.process(outputStream0, outputStream0);
  }
}
