/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 02:05:59 GMT 2018
 */

package spark.embeddedserver.jetty;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import spark.embeddedserver.jetty.EmbeddedJettyFactory;
import spark.route.Routes;
import spark.staticfiles.StaticFilesConfiguration;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmbeddedJettyFactory_ESTest extends EmbeddedJettyFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmbeddedJettyFactory embeddedJettyFactory0 = new EmbeddedJettyFactory();
      Routes routes0 = mock(Routes.class, new ViolatedAssumptionAnswer());
      StaticFilesConfiguration staticFilesConfiguration0 = mock(StaticFilesConfiguration.class, new ViolatedAssumptionAnswer());
      embeddedJettyFactory0.create(routes0, staticFilesConfiguration0, true);
      StaticFilesConfiguration staticFilesConfiguration1 = mock(StaticFilesConfiguration.class, new ViolatedAssumptionAnswer());
      embeddedJettyFactory0.create((Routes) null, staticFilesConfiguration1, false);
      StaticFilesConfiguration staticFilesConfiguration2 = mock(StaticFilesConfiguration.class, new ViolatedAssumptionAnswer());
      embeddedJettyFactory0.create((Routes) null, staticFilesConfiguration2, true);
      StaticFilesConfiguration staticFilesConfiguration3 = mock(StaticFilesConfiguration.class, new ViolatedAssumptionAnswer());
      embeddedJettyFactory0.create((Routes) null, staticFilesConfiguration3, false);
  }
}
