/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 00:53:40 GMT 2018
 */

package spark.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import spark.utils.ClassUtils;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClassUtils_ESTest extends ClassUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ClassLoader classLoader0 = ClassUtils.getDefaultClassLoader();
      try { 
        ClassUtils.forName("uBU-mSEf", classLoader0);
        fail("Expecting exception: ClassNotFoundException");
      
      } catch(ClassNotFoundException e) {
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ClassLoader classLoader0 = ClassUtils.getDefaultClassLoader();
      try { 
        ClassUtils.forName("gF*udu]~u8 Rw[]", classLoader0);
        fail("Expecting exception: ClassNotFoundException");
      
      } catch(ClassNotFoundException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ClassLoader classLoader0 = ClassUtils.getDefaultClassLoader();
      Class<?> class0 = ClassUtils.forName("spark.utils.ClassUtils", classLoader0);
      assertFalse(class0.isAnnotation());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ClassLoader classLoader0 = ClassUtils.getDefaultClassLoader();
      // Undeclared exception!
      try { 
        ClassUtils.forName((String) null, classLoader0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Name must not be null
         //
         verifyException("spark.utils.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Class<?> class0 = ClassUtils.resolvePrimitiveClassName("");
      assertNull(class0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Class<?> class0 = ClassUtils.resolvePrimitiveClassName("6/(:-L|p`]7ZTu'ZdHg");
      assertNull(class0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = ClassUtils.classPackageAsResourcePath((Class<?>) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Class<Long> class0 = Long.class;
      String string0 = ClassUtils.classPackageAsResourcePath(class0);
      assertEquals("java/lang", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Class<?> class0 = ClassUtils.resolvePrimitiveClassName((String) null);
      assertNull(class0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      try { 
        ClassUtils.forName("-)w+m", (ClassLoader) null);
        fail("Expecting exception: ClassNotFoundException");
      
      } catch(ClassNotFoundException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ClassLoader classLoader0 = ClassUtils.getDefaultClassLoader();
      try { 
        ClassUtils.forName("[L7;", classLoader0);
        fail("Expecting exception: ClassNotFoundException");
      
      } catch(ClassNotFoundException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ClassLoader classLoader0 = ClassUtils.getDefaultClassLoader();
      try { 
        ClassUtils.forName("[L[Ly2D&m1]^z\"mGT<", classLoader0);
        fail("Expecting exception: ClassNotFoundException");
      
      } catch(ClassNotFoundException e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ClassLoader classLoader0 = ClassUtils.getDefaultClassLoader();
      try { 
        ClassUtils.forName("K;.VOw[pzZ", classLoader0);
        fail("Expecting exception: ClassNotFoundException");
      
      } catch(ClassNotFoundException e) {
      }
  }
}
