/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 02:04:56 GMT 2018
 */

package spark.embeddedserver.jetty.websocket;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.jetty.websocket.api.WebSocketAdapter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import spark.embeddedserver.jetty.websocket.WebSocketCreatorFactory;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WebSocketCreatorFactory_ESTest extends WebSocketCreatorFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        WebSocketCreatorFactory.create((Class<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Class<WebSocketAdapter> class0 = WebSocketAdapter.class;
      WebSocketCreatorFactory.SparkWebSocketCreator webSocketCreatorFactory_SparkWebSocketCreator0 = (WebSocketCreatorFactory.SparkWebSocketCreator)WebSocketCreatorFactory.create(class0);
      WebSocketAdapter webSocketAdapter0 = (WebSocketAdapter)webSocketCreatorFactory_SparkWebSocketCreator0.getHandler();
      assertFalse(webSocketAdapter0.isConnected());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WebSocketCreatorFactory webSocketCreatorFactory0 = new WebSocketCreatorFactory();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      // Undeclared exception!
      try { 
        WebSocketCreatorFactory.create(class0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // WebSocket handler must implement 'WebSocketListener' or be annotated as '@WebSocket'
         //
         verifyException("spark.embeddedserver.jetty.websocket.WebSocketCreatorFactory", e);
      }
  }
}
