/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 00:55:18 GMT 2018
 */

package spark.embeddedserver;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import spark.embeddedserver.NotSupportedException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NotSupportedException_ESTest extends NotSupportedException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        NotSupportedException.raise("SRvpUji];8(q_xdZbU", "3&jSU}bUl`\u0006E");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 'SRvpUji];8(q_xdZbU' doesn't support '3&jSU}bUl`\u0006E'
         //
         verifyException("spark.embeddedserver.NotSupportedException", e);
      }
  }
}
