/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 00:54:27 GMT 2018
 */

package spark.route;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import spark.route.Routes;
import spark.route.ServletRoutes;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ServletRoutes_ESTest extends ServletRoutes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Routes routes0 = ServletRoutes.get();
      Routes routes1 = ServletRoutes.get();
      assertSame(routes1, routes0);
  }
}
