/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 02:07:09 GMT 2018
 */

package spark;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import spark.Redirect;
import spark.Routable;
import spark.Service;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Redirect_ESTest extends Redirect_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Service service0 = Service.ignite();
      service0.redirect.put("~.s)n~{Quf<]", "");
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Service service0 = Service.ignite();
      service0.redirect.get((String) null, "org.eclipse.jetty.http.MetaData$Request");
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Service service0 = Service.ignite();
      Redirect.Status redirect_Status0 = Redirect.Status.USE_PROXY;
      service0.redirect.post("spark.Redirect", "spark.Redirect", redirect_Status0);
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Redirect redirect0 = Redirect.create((Routable) null);
      // Undeclared exception!
      try { 
        redirect0.put("TEMPORARY_REDIRECT", "TEMPORARY_REDIRECT");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("spark.Redirect", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Redirect redirect0 = Redirect.create((Routable) null);
      // Undeclared exception!
      try { 
        redirect0.post("SEE_OTHER", "SEE_OTHER");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("spark.Redirect", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Redirect redirect0 = Redirect.create((Routable) null);
      // Undeclared exception!
      try { 
        redirect0.get("yyyy_mm_dd", "yyyy_mm_dd");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("spark.Redirect", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Redirect redirect0 = Redirect.create((Routable) null);
      // Undeclared exception!
      try { 
        redirect0.any((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("spark.Redirect", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Service service0 = Service.ignite();
      Redirect.Status redirect_Status0 = Redirect.Status.SWITCH_PROXY;
      service0.redirect.any("&'C", "4I]gLqGk85", redirect_Status0);
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Service service0 = Service.ignite();
      Redirect.Status redirect_Status0 = Redirect.Status.USE_PROXY;
      service0.redirect.delete("^Cm15", "^Cm15", redirect_Status0);
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Service service0 = Service.ignite();
      Redirect.Status redirect_Status0 = Redirect.Status.USE_PROXY;
      service0.redirect.get("cyfV<j]eP7Mu1bkw", "REF", redirect_Status0);
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Service service0 = Service.ignite();
      Redirect.Status redirect_Status0 = Redirect.Status.SWITCH_PROXY;
      service0.redirect.put("$bS{a", "s-:%[D)", redirect_Status0);
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Redirect.Status redirect_Status0 = Redirect.Status.SWITCH_PROXY;
      int int0 = redirect_Status0.intValue();
      assertEquals(306, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Service service0 = Service.ignite();
      service0.redirect.post("$bS{a", "yysO4u1>Y[#");
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Service service0 = Service.ignite();
      service0.redirect.delete("cyfV<j]eP7Mu1bkw", "REF");
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Service service0 = Service.ignite();
      service0.redirect.any("9g;u0", "5dr<9Ba*hj");
      assertEquals(4567, Service.SPARK_DEFAULT_PORT);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Redirect redirect0 = Redirect.create((Routable) null);
      Redirect.Status redirect_Status0 = Redirect.Status.MOVED_PERMANENTLY;
      // Undeclared exception!
      try { 
        redirect0.post("L%:MNU}@Bm6xY1mh", "L%:MNU}@Bm6xY1mh", redirect_Status0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("spark.Redirect", e);
      }
  }
}
